"""Unit tests for XLMem metrics using hand-computed fixtures.

Hand-computed values are derived mathematically per METRICS_SPEC.md,
never generated by an LLM.
"""

from __future__ import annotations

import pytest
from xlmem.benchmark.facts import Fact, Memory, ProbeResult
from xlmem.scoring.duplication import compute_duplication_rate, compute_false_merge_rate
from xlmem.scoring.retrieval import (
    compute_encoding_asymmetry,
    compute_ltg,
    compute_recall_at_k,
    compute_write_fidelity,
)
from xlmem.scoring.staleness import compute_staleness_rate


@pytest.fixture
def hand_computed_facts() -> list[Fact]:
    """5 hand-crafted facts exactly per METRICS_SPEC.md section 4."""
    return [
        Fact(
            id="f_1",
            domain="health",
            entity="user",
            relation="allergic_to",
            value="peanuts",
            surface={"hi": "मुझे मूंगफली से एलर्जी है।", "en": "I am allergic to peanuts."},
        ),
        Fact(
            id="f_2",
            domain="travel",
            entity="user",
            relation="lives_in",
            value="pune",
            surface={"hi": "मैं पुणे में रहता हूँ।", "en": "I live in Pune."},
            update_data={"updated_value": "mumbai"},
        ),
        Fact(
            id="f_3",
            domain="work",
            entity="user",
            relation="works_at",
            value="infosys",
            surface={"hi": "मैं इंफोसिस में काम करता हूँ।", "en": "I work at Infosys."},
        ),
        Fact(
            id="f_4",
            domain="language",
            entity="user",
            relation="speaks_language",
            value="marathi",
            surface={"hi": "मैं मराठी बोलता हूँ।", "en": "I speak Marathi."},
        ),
        Fact(
            id="f_5",
            domain="family",
            entity="user",
            relation="owns_pet",
            value="golden_retriever",
            surface={"hi": "मेरे पास गोल्डन रिट्रीवर कुत्ता है।", "en": "I have a golden retriever dog."},
        ),
    ]


@pytest.fixture
def hand_computed_distractor_pairs(hand_computed_facts: list[Fact]) -> list[tuple[Fact, Fact]]:
    """Near-miss pair: f_1 (user, allergic_to, peanuts) and distractor (sister, allergic_to, peanuts)."""
    f1 = hand_computed_facts[0]
    f1_dist = Fact(
        id="f_1_dist",
        domain="health",
        entity="user_sister",
        relation="allergic_to",
        value="peanuts",
        surface={"hi": "मेरी बहन को मूंगफली से एलर्जी है।", "en": "My sister is allergic to peanuts."},
        distractor_of="f_1",
    )
    return [(f1, f1_dist)]


@pytest.fixture
def hand_computed_memories() -> list[Memory]:
    """Memory store dump matching METRICS_SPEC.md Section 4:

    - Entry 1: 'User has peanut allergy' -> matches f_1
    - Entry 2: 'User lives in Pune' -> matches f_2
    - Entry 3: 'User works at Infosys' -> matches f_3
    - Entry 4: 'User works at Infosys Bangalore' -> duplicate match for f_3
    - Entry 5: 'User has a golden retriever' -> matches f_5
    (Notice f_4 'marathi' is missing from the store entirely!)
    """
    return [
        Memory(raw_id="m1", text="User has peanut allergy"),
        Memory(raw_id="m2", text="User lives in Pune"),
        Memory(raw_id="m3", text="User works at Infosys"),
        Memory(raw_id="m4", text="User works at Infosys Bangalore"),
        Memory(raw_id="m5", text="User has a golden retriever"),
    ]


def test_write_fidelity_hand_computed(
    hand_computed_facts: list[Fact],
    hand_computed_memories: list[Memory],
) -> None:
    """Hand-computed: 4 out of 5 facts stored -> WF = 4/5 = 0.80.

    f_4 ('marathi') was not stored.
    """
    wf, written_ids = compute_write_fidelity(hand_computed_facts, hand_computed_memories)
    assert wf == pytest.approx(0.80, abs=1e-4)
    assert set(written_ids) == {"f_1", "f_2", "f_3", "f_5"}
    assert "f_4" not in written_ids


def test_duplication_rate_hand_computed(
    hand_computed_facts: list[Fact],
    hand_computed_memories: list[Memory],
) -> None:
    """Hand-computed DR:

    f_1: 1 match (excess 0)
    f_2: 1 match (excess 0)
    f_3: 2 matches (excess 1)
    f_4: 0 matches (excess 0)
    f_5: 1 match (excess 0)
    Total excess = 1 across 5 facts -> DR = 1/5 = 0.20.
    """
    dr = compute_duplication_rate(hand_computed_facts, hand_computed_memories)
    assert dr == pytest.approx(0.20, abs=1e-4)


def test_false_merge_rate_hand_computed(
    hand_computed_distractor_pairs: list[tuple[Fact, Fact]],
    hand_computed_memories: list[Memory],
) -> None:
    """Hand-computed FMR: No collapsed memory records -> FMR = 0/1 = 0.00."""
    fmr = compute_false_merge_rate(hand_computed_distractor_pairs, hand_computed_memories)
    assert fmr == pytest.approx(0.00, abs=1e-4)

    # Now create a collapsed memory
    collapsed_store = [
        Memory(raw_id="mc", text="User and user's sister are both allergic to peanuts."),
    ]
    # For a value-shift pair where both values merge:
    f_base = Fact(id="b", domain="h", entity="u", relation="r", value="apple", surface={"en": "apple"})
    f_dist = Fact(id="d", domain="h", entity="u", relation="r", value="orange", surface={"en": "orange"}, distractor_of="b")
    merged_store = [Memory(raw_id="m_merged", text="User likes apple and orange.")]
    fmr_merged = compute_false_merge_rate([(f_base, f_dist)], merged_store)
    assert fmr_merged == pytest.approx(1.00, abs=1e-4)


def test_recall_at_k_and_write_first_ordering(
    hand_computed_facts: list[Fact],
    hand_computed_memories: list[Memory],
) -> None:
    """Hand-computed Recall:

    Probe results on written facts {f_1, f_2, f_3, f_5}:
      f_1 -> retrieves m1 ('peanut') -> HIT
      f_2 -> retrieves unrelated -> MISS
      f_3 -> retrieves m3 ('Infosys') -> HIT
      f_5 -> retrieves m5 ('golden retriever') -> HIT
    Strict hits = 3/4 = 0.75 on written facts.

    CRITICAL INVARIANT CHECK:
    If f_4 (missing from dump) were wrongly counted as a retrieval failure,
    recall would be 3/5 = 0.60. Write-first filtering ensures 3/4 = 0.75.
    """
    probe_results = [
        ProbeResult(fact_id="f_1", store_lang="hi", probe_lang="en", retrieved=[hand_computed_memories[0]], response="peanuts", hit_strict=True),
        ProbeResult(fact_id="f_2", store_lang="hi", probe_lang="en", retrieved=[Memory(raw_id="x", text="unrelated")], response="I don't know", hit_strict=False),
        ProbeResult(fact_id="f_3", store_lang="hi", probe_lang="en", retrieved=[hand_computed_memories[2]], response="Infosys", hit_strict=True),
        ProbeResult(fact_id="f_4", store_lang="hi", probe_lang="en", retrieved=[], response="No idea", hit_strict=False),
        ProbeResult(fact_id="f_5", store_lang="hi", probe_lang="en", retrieved=[hand_computed_memories[4]], response="golden retriever", hit_strict=True),
    ]

    _, written_ids = compute_write_fidelity(hand_computed_facts, hand_computed_memories)

    # Evaluated on written facts: 3 hits out of 4 written
    recall_written = compute_recall_at_k(hand_computed_facts, probe_results, k=1, mode="strict", eligible_fact_ids=set(written_ids))
    assert recall_written == pytest.approx(0.75, abs=1e-4)

    # Raw unpartitioned recall on all 5 facts would be 3/5 = 0.60
    recall_raw = compute_recall_at_k(hand_computed_facts, probe_results, k=1, mode="strict", eligible_fact_ids=None)
    assert recall_raw == pytest.approx(0.60, abs=1e-4)


def test_ltg_hand_computed() -> None:
    """Hand-computed LTG:

    Same-lang recalls: [0.90, 0.86] -> mean = 0.88
    Cross-lang recalls: [0.65, 0.71] -> mean = 0.68
    LTG = 0.88 - 0.68 = 0.20
    """
    ltg = compute_ltg(same_lang_recalls=[0.90, 0.86], cross_lang_recalls=[0.65, 0.71])
    assert ltg == pytest.approx(0.20, abs=1e-4)


def test_encoding_asymmetry_hand_computed() -> None:
    """Hand-computed EA:

    recall(store=hi) = 0.60
    recall(store=en) = 0.75
    EA = 0.60 - 0.75 = -0.15 (English storage is superior by 15 percentage points)
    """
    ea = compute_encoding_asymmetry(recall_stored_hi=0.60, recall_stored_en=0.75)
    assert ea == pytest.approx(-0.15, abs=1e-4)


def test_staleness_rate_hand_computed(hand_computed_facts: list[Fact]) -> None:
    """Hand-computed SR:

    f_2 updated from 'pune' to 'mumbai'.
    Re-probe returns: 'You live in Pune and Mumbai.' -> contains stale value 'pune'!
    SR = 1/1 = 1.00 (100%).
    """
    f2 = hand_computed_facts[1]
    reprobe_stale = [
        ProbeResult(
            fact_id="f_2",
            store_lang="hi",
            probe_lang="en",
            retrieved=[Memory(raw_id="m_u", text="User lives in Mumbai and Pune")],
            response="You live in Pune and Mumbai.",
            hit_strict=False,
        )
    ]
    sr = compute_staleness_rate(corrected_facts=[f2], reprobe_results=reprobe_stale)
    assert sr == pytest.approx(1.00, abs=1e-4)

    # When stale value is completely cleared:
    reprobe_clean = [
        ProbeResult(
            fact_id="f_2",
            store_lang="hi",
            probe_lang="en",
            retrieved=[Memory(raw_id="m_u", text="User lives in Mumbai")],
            response="You live in Mumbai.",
            hit_strict=True,
        )
    ]
    sr_clean = compute_staleness_rate(corrected_facts=[f2], reprobe_results=reprobe_clean)
    assert sr_clean == pytest.approx(0.00, abs=1e-4)
